--- #YAML:1.0
name:               CGI-Alternatives
version:            0.01
abstract:           Documentation for alternative solutions to CGI.pm
author:
    - Lee Johnson <leejo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:           0
    Test::Pod:            1.48
    Test::Pod::Coverage:  1.08
requires:  {}
resources:
    bugtracker:  https://github.com/leejo/cgi-alterntatives/issues
    homepage:    https://metacpan.org/module/CGI::Alternatives
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/leejo/cgi-alternatives
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
