---
abstract: 'Documentation for alternative solutions to CGI.pm'
author:
  - 'Lee Johnson <leejo@cpan.org>'
build_requires:
  Test::More: '0'
  Test::Pod: '1.48'
  Test::Pod::Coverage: '1.08'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CGI-Alternatives
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: https://github.com/leejo/cgi-alternatives/issues
  homepage: https://metacpan.org/module/CGI::Alternatives
  license: http://dev.perl.org/licenses/
  repository: https://github.com/leejo/cgi-alternatives
version: '0.09'
